services:
  api:
    image: ghcr.io/locmaymo/api-stats:latest
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
    depends_on:
      - mongo
    networks:
      - api_network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - api_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORT=${PORT}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - api
    networks:
      - api_network

volumes:
  mongo_data:

networks:
  api_network: