version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

volumes:
  mongo_data: